# parameter.yml — Environment-specific parameterization for fabric-cicd
#
# Docs: https://microsoft.github.io/fabric-cicd/parameterization/

find_replace:
  - find_value: "334687d9-c5a3-4af6-a9b1-9c02bad79934"
    replace_value:
      DEV: "334687d9-c5a3-4af6-a9b1-9c02bad79934"
      QA: "9b6c012c-1c20-4807-9feb-a7703a7671bd"
      PROD: "7d836180-43af-494d-80e9-de50ed5f8529"
























